#!/usr/bin/env python3
"""
Context-aware data analyzer for ChimariData.
Consumes structured JSON generated by the PythonProcessor bridge,
executes descriptive statistics, correlations, regression, clustering,
and qualitative summarization, then emits a JSON payload consumed by the
analysis-execution service.
"""

from __future__ import annotations

import json
import os
import sys
import warnings
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

try:
    from sklearn.cluster import KMeans
    from sklearn.linear_model import LinearRegression
    from sklearn.metrics import r2_score, silhouette_score

    SKLEARN_AVAILABLE = True
except Exception:  # pragma: no cover - safeguard if sklearn missing
    SKLEARN_AVAILABLE = False
    LinearRegression = None
    KMeans = None
    silhouette_score = None
    r2_score = None


def to_serializable(value: Any) -> Any:
    if isinstance(value, (np.integer, np.int64)):
        return int(value)
    if isinstance(value, (np.floating, np.float32, np.float64)):
        return float(value)
    if isinstance(value, (np.ndarray, list, tuple)):
        return [to_serializable(v) for v in value]
    if isinstance(value, (pd.Timestamp, pd.Timedelta)):
        return value.isoformat()
    if isinstance(value, (pd.Series, pd.Index)):
        return value.tolist()
    return value


def read_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def resolve_rows(dataset_payload: Dict[str, Any]) -> Optional[List[Any]]:
    candidates = [
        dataset_payload.get("rows"),
        dataset_payload.get("data"),
        dataset_payload.get("preview"),
        dataset_payload.get("records"),
    ]

    for candidate in candidates:
        if not candidate:
            continue
        if isinstance(candidate, list):
            return candidate
        if isinstance(candidate, dict):
            if isinstance(candidate.get("rows"), list):
                return candidate["rows"]
            if isinstance(candidate.get("records"), list):
                return candidate["records"]
    return None


def load_dataframe(input_payload: Dict[str, Any]) -> pd.DataFrame:
    dataset_payload = input_payload.get("dataset") or input_payload
    rows = resolve_rows(dataset_payload)

    if rows and len(rows) > 0:
        first = rows[0]
        if isinstance(first, dict):
            return pd.DataFrame(rows)

        schema = dataset_payload.get("schema")
        if schema and isinstance(first, (list, tuple)):
            columns = list(schema.keys())[: len(first)]
            return pd.DataFrame(rows, columns=columns)

    file_path = dataset_payload.get("filePath") or dataset_payload.get("storageUri")
    if not file_path:
        raise ValueError("No dataset rows or filePath provided for analysis")

    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Dataset file not found: {file_path}")

    _, ext = os.path.splitext(file_path.lower())
    if ext in (".xlsx", ".xls"):
        return pd.read_excel(file_path)
    if ext in (".csv", ".txt"):
        return pd.read_csv(file_path)
    if ext in (".json", ".ndjson"):
        return pd.read_json(file_path, lines=ext == ".ndjson")

    raise ValueError(f"Unsupported file extension for analysis: {ext}")


def normalize_analysis_types(config: Dict[str, Any]) -> List[str]:
    requested = config.get("analysisTypes") or config.get("analysis_types")
    if not requested:
        return ["descriptive", "correlation", "regression", "clustering", "time-series"]
    return [str(value).lower() for value in requested]


def compute_descriptive(df: pd.DataFrame) -> Dict[str, Any]:
    numeric_df = df.select_dtypes(include=[np.number])
    summary = {
        "rowCount": int(len(df)),
        "columnCount": int(len(df.columns)),
        "missingValues": int(df.isna().sum().sum()),
        "columnTypes": {col: str(dtype) for col, dtype in zip(df.columns, df.dtypes)},
    }

    if not numeric_df.empty:
        numeric_summary = numeric_df.describe().transpose().applymap(to_serializable).to_dict()
        summary["numericSummary"] = numeric_summary

    return summary


def compute_correlations(df: pd.DataFrame, limit: int = 5) -> List[Dict[str, Any]]:
    numeric_df = df.select_dtypes(include=[np.number])
    if numeric_df.shape[1] < 2:
        return []

    corr_matrix = numeric_df.corr()
    results: List[Dict[str, Any]] = []
    columns = numeric_df.columns.tolist()

    for i in range(len(columns)):
        for j in range(i + 1, len(columns)):
            corr_value = corr_matrix.iloc[i, j]
            if pd.isna(corr_value):
                continue
            results.append(
                {
                    "variable1": columns[i],
                    "variable2": columns[j],
                    "correlation": float(corr_value),
                }
            )

    results.sort(key=lambda item: abs(item["correlation"]), reverse=True)
    return results[:limit]


def compute_regression(df: pd.DataFrame, numeric_columns: List[str]) -> Optional[Dict[str, Any]]:
    if not SKLEARN_AVAILABLE or len(numeric_columns) < 2:
        return None

    target = numeric_columns[0]
    features = numeric_columns[1:]

    clean_df = df[numeric_columns].dropna()
    if clean_df.shape[0] < 10:
        return None

    X = clean_df[features]
    y = clean_df[target]

    model = LinearRegression()
    model.fit(X, y)

    r2 = float(model.score(X, y))
    coefficients = {feature: float(coef) for feature, coef in zip(features, model.coef_)}

    return {
        "analysis_type": "regression",
        "target": target,
        "features": features,
        "r2": r2,
        "coefficients": coefficients,
        "sampleSize": int(len(X)),
        "interpretation": f"Model explains {round(r2 * 100, 1)}% of the variation in {target}",
    }


def compute_clustering(df: pd.DataFrame, numeric_columns: List[str]) -> Optional[Dict[str, Any]]:
    if not SKLEARN_AVAILABLE or len(numeric_columns) < 2:
        return None

    numeric_df = df[numeric_columns].dropna()
    if numeric_df.shape[0] < 15:
        return None

    cluster_count = max(2, min(4, numeric_df.shape[0] // 10))
    model = KMeans(n_clusters=cluster_count, n_init=10, random_state=42)
    labels = model.fit_predict(numeric_df)

    silhouette = None
    if silhouette_score:
        silhouette = float(silhouette_score(numeric_df, labels))

    centroids = [
        {column: float(value) for column, value in zip(numeric_columns, center)}
        for center in model.cluster_centers_
    ]

    return {
        "analysis_type": "clustering",
        "nClusters": cluster_count,
        "silhouetteScore": silhouette,
        "centroids": centroids,
        "description": f"Identified {cluster_count} behavior group(s) across {len(numeric_columns)} numeric fields",
    }


def detect_datetime_column(df: pd.DataFrame) -> Optional[str]:
    for column in df.columns:
        series = df[column]
        if pd.api.types.is_datetime64_any_dtype(series):
            return column

        if series.dtype == object and "date" in column.lower():
            converted = pd.to_datetime(series, errors="coerce")
            if converted.notna().mean() > 0.7:
                df[column] = converted
                return column
    return None


def compute_time_series(df: pd.DataFrame) -> Optional[Dict[str, Any]]:
    date_column = detect_datetime_column(df)
    if not date_column:
        return None

    numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()
    if not numeric_columns:
        return None

    value_column = numeric_columns[0]
    ts_df = df[[date_column, value_column]].dropna().sort_values(date_column)
    if ts_df.shape[0] < 6:
        return None

    midpoint = len(ts_df) // 2
    first_half = ts_df[value_column].iloc[:midpoint].mean()
    second_half = ts_df[value_column].iloc[midpoint:].mean()
    trend = "increasing" if second_half > first_half else "decreasing"

    return {
        "column": value_column,
        "dateColumn": date_column,
        "trend": trend,
        "startValue": float(ts_df[value_column].iloc[0]),
        "endValue": float(ts_df[value_column].iloc[-1]),
        "changePct": float(((second_half - first_half) / max(abs(first_half), 1e-9)) * 100),
    }


def summarize_text_columns(df: pd.DataFrame, limit: int = 3) -> List[Dict[str, Any]]:
    text_columns = df.select_dtypes(include=["object"]).columns
    insights: List[Dict[str, Any]] = []

    for column in text_columns:
        series = df[column].dropna().astype(str).str.strip()
        if series.empty:
            continue

        value_counts = series.value_counts().head(limit)
        top_values = [
            {"value": value, "count": int(count)}
            for value, count in value_counts.items()
        ]

        if not top_values:
            continue

        confidence = min(95, 60 + int((top_values[0]["count"] / max(len(series), 1)) * 40))

        insights.append(
            {
                "column": column,
                "title": f"Top responses for {column}",
                "summary": ", ".join(f"{item['value']} ({item['count']})" for item in top_values),
                "values": top_values,
                "impact": "Medium",
                "confidence": confidence,
                "category": "Qualitative",
            }
        )

    return insights


def build_visualizations(correlations: List[Dict[str, Any]], text_insights: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    visualizations: List[Dict[str, Any]] = []

    if correlations:
        visualizations.append(
            {
                "type": "heatmap",
                "title": "Correlation highlights",
                "data": correlations,
            }
        )

    if text_insights:
        visualizations.append(
            {
                "type": "bar",
                "title": text_insights[0]["title"],
                "series": text_insights[0]["values"],
            }
        )

    return visualizations[:3]


def build_output(
    df: pd.DataFrame,
    analysis_types: List[str],
) -> Dict[str, Any]:
    numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()

    descriptive = compute_descriptive(df) if "descriptive" in analysis_types else None
    correlations = compute_correlations(df) if "correlation" in analysis_types else []
    regression = compute_regression(df, numeric_columns) if "regression" in analysis_types else None
    clustering = compute_clustering(df, numeric_columns) if "clustering" in analysis_types else None
    time_series = compute_time_series(df) if "time-series" in analysis_types else None
    text_insights = summarize_text_columns(df)

    visualizations = build_visualizations(correlations, text_insights)

    return {
        "rowCount": int(len(df)),
        "columnCount": int(len(df.columns)),
        "descriptive": descriptive,
        "correlations": correlations,
        "regression": regression,
        "clustering": clustering,
        "timeSeries": time_series,
        "textInsights": text_insights,
        "visualizations": visualizations,
    }


def write_output(path: str, payload: Dict[str, Any]) -> None:
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, default=to_serializable)


def main() -> None:
    if len(sys.argv) != 4:
        print("Usage: python data_analyzer.py <input_file> <config_file> <output_file>")
        sys.exit(1)

    input_file, config_file, output_file = sys.argv[1:4]

    try:
        input_payload = read_json(input_file)
        config = read_json(config_file)
        analysis_types = normalize_analysis_types(config)

        df = load_dataframe(input_payload)

        results = build_output(df, analysis_types)

        write_output(
            output_file,
            {
                "success": True,
                "data": results,
                "visualizations": results.get("visualizations", []),
            },
        )

        print("Analysis completed successfully")

    except Exception as exc:  # pragma: no cover - safety net
        write_output(
            output_file,
            {
                "success": False,
                "error": str(exc),
                "data": None,
                "visualizations": [],
            },
        )
        print(f"Analysis failed: {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()

